export enum TypeEnum {
    Bug = 1,
    Dark = 2,
    Dragon = 3,
    Electric = 4,
    Fairy = 5,
    Fighting = 6,
    Fire = 7,
    Flying = 8,
    Ghost = 9,
    Grass = 10,
    Ground = 11,
    Ice = 12,
    Normal = 13,
    Poison = 14,
    Psychic = 15,
    Rock = 16,
    Steel = 17,
    Water = 18,
}

export const TypeEnumLabel: Record<TypeEnum, string> = {
    [TypeEnum.Bug]: "Bug",
    [TypeEnum.Dark]: "Dark",
    [TypeEnum.Dragon]: "Dragon",
    [TypeEnum.Electric]: "Electric",
    [TypeEnum.Fairy]: "Fairy",
    [TypeEnum.Fighting]: "Fighting",
    [TypeEnum.Fire]: "Fire",
    [TypeEnum.Flying]: "Flying",
    [TypeEnum.Ghost]: "Ghost",
    [TypeEnum.Grass]: "Grass",
    [TypeEnum.Ground]: "Ground",
    [TypeEnum.Ice]: "Ice",
    [TypeEnum.Normal]: "Normal",
    [TypeEnum.Poison]: "Poison",
    [TypeEnum.Psychic]: "Psychic",
    [TypeEnum.Rock]: "Rock",
    [TypeEnum.Steel]: "Steel",
    [TypeEnum.Water]: "Water",
};
